name: ~test and lint Rosetta

on:
  # Manual trigger
  workflow_dispatch:
  # Called from another workflow
  workflow_call:
    inputs:
      ROSETTA_IMAGE_TAG:
        type: string
        description: Tag of image from https://github.com/NVIDIA/JAX-Toolbox/pkgs/container/rosetta
        default: latest
        required: false

jobs:
  rosetta-tests:
    strategy:
      matrix:
        MARKERS: ["", "-m integration"]
      fail-fast: false
    runs-on: [self-hosted, 2GPU]
    steps:
      - name: Print host information
        run: |
          hostname
          date
          nvcc --version
          nvidia-smi -L
          nvidia-smi

      - name: Print environment variables
        run: |
          env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          CONTAINER_REPOSITORY=`echo ${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          IMAGE_ROSETTA="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/rosetta"
          echo "IMAGE_ROSETTA=${IMAGE_ROSETTA}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker image
        run: |
          set -x
          docker run --runtime=nvidia --gpus '"device=0,1"' ${{ env.IMAGE_ROSETTA }} sh -c "pip install '/opt/rosetta[test]' && pytest -n3 /opt/rosetta ${{ matrix.MARKERS }}"

  rosetta-lint-check:
    runs-on: [self-hosted]
    steps:
      - name: Print host information
        run: |
          hostname
          date

      - name: Print environment variables
        run: |
          env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          CONTAINER_REPOSITORY=`echo ${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          IMAGE_ROSETTA="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/rosetta"
          echo "IMAGE_ROSETTA=${IMAGE_ROSETTA}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker image
        run: |
          set -x
          docker run ${{ env.IMAGE_ROSETTA }} sh -c "pip install -e '/opt/rosetta[lint]' && ruff /opt/rosetta"


