name: Nightly Rosetta build

on:
  workflow_run:
    workflows: [Nightly T5X build]
    types: [completed]
  workflow_dispatch:
    inputs:
      PUBLISH:
        type: boolean
        description: Publish dated images and update the 'latest' tag?
        default: false
        required: false

env:
  TARGET: rosetta
  DOCKER_REGISTRY: ghcr.io/nvidia

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  metadata:
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    outputs:
      BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
    steps:
      - name: Set build date
        id: date
        shell: bash -x -e {0}
        run: |
          BUILD_DATE=$(TZ='US/Los_Angeles' date '+%Y-%m-%d')
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_OUTPUT

  build:
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch'
    needs: metadata
    uses: ./.github/workflows/_build_rosetta.yaml
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
    secrets: inherit

  publish:
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' && inputs.PUBLISH)
    runs-on: ubuntu-22.04
    needs: [metadata, build]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.TARGET }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=nightly-${{ needs.metadata.outputs.BUILD_DATE }},priority=900
            type=raw,value=latest,priority=1000
            # type=ref,event=branch
            # type=ref,event=pr

      - name: Create manifest
        shell: bash -x -e {0}
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}"); do
            docker manifest create $tag ${{ needs.build.outputs.DOCKER_TAGS }}
            docker manifest push $tag
          done

      - name: Generate outputs and artifacts
        shell: bash -x -e {0}
        run: |
          echo "${{ steps.meta.outputs.tags }}" > image-tags-${{ env.TARGET }}.txt

      - name: Upload image tags as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image-tags-${{ env.TARGET }}
          path: image-tags-${{ env.TARGET }}.txt

  if-upstream-failed:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure') && github.event_name != 'workflow_dispatch'
    steps:
      - run: echo 'Upstream workflow failed, aborting run' && exit 1
